# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Huski < Formula
  desc "TUI ASCII diagram editor — object-based, Vim modal, Catppuccin theme"
  homepage "https://github.com/artw/huski"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artw/huski/releases/download/v0.1.1/huski-0.1.1-darwin-amd64.tar.xz"
      sha256 "52292db7a9228b5cc98a8df30472c247dfc45bb6b2045943fc21941dbcf4ac9d"

      define_method(:install) do
        bin.install "huski"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artw/huski/releases/download/v0.1.1/huski-0.1.1-darwin-arm64.tar.xz"
      sha256 "767b77e130474748f5b443ed16f33a28843aab98f476f8c6263f9d01503572e6"

      define_method(:install) do
        bin.install "huski"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artw/huski/releases/download/v0.1.1/huski-0.1.1-linux-amd64.tar.xz"
      sha256 "d84fe04bb35902b5ef6ee34f699f8e512174ac4934a48a2c889004a29fb4ac2c"
      define_method(:install) do
        bin.install "huski"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artw/huski/releases/download/v0.1.1/huski-0.1.1-linux-arm64.tar.xz"
      sha256 "9a621825048eff8ff6d9c054d41473d0ae853b35b9780f39d0c000ae3e89f863"
      define_method(:install) do
        bin.install "huski"
      end
    end
  end

  test do
    system "#{bin}/huski", "--help"
  end
end
