# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Huski < Formula
  desc "TUI ASCII diagram editor — object-based, Vim modal, Catppuccin theme"
  homepage "https://github.com/artw/huski"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artw/huski/releases/download/v0.1.0/huski-0.1.0-darwin-amd64.tar.xz"
      sha256 "0788d7a1088821e46d1b4ddd3e39d98d28649e7a1325e4c4659c8e81dc933239"

      define_method(:install) do
        bin.install "huski"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artw/huski/releases/download/v0.1.0/huski-0.1.0-darwin-arm64.tar.xz"
      sha256 "84b5a4a52baa4b94156cd3db6a3072b35641c7c42a78f2752e410706ab9e2810"

      define_method(:install) do
        bin.install "huski"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artw/huski/releases/download/v0.1.0/huski-0.1.0-linux-amd64.tar.xz"
      sha256 "c5e89bbb0fd81594523c5cf71a7907dfa235c3225f3861bf50f429df785f117e"
      define_method(:install) do
        bin.install "huski"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artw/huski/releases/download/v0.1.0/huski-0.1.0-linux-arm64.tar.xz"
      sha256 "c14e971f828ba168c4a2a6347b4fc3794d2ac28323e0bab0e6d6d390f6cc2b99"
      define_method(:install) do
        bin.install "huski"
      end
    end
  end

  test do
    system "#{bin}/huski", "--help"
  end
end
